"""Fig 6: 定性样例。左列 SLAKE 测试图 + 问题 + 各模型回答; 末行 (可选) IU X-Ray 胸片 + 模型生成报告 vs 真实报告。

输入:
  data/raw/SLAKE/test.json, data/raw/SLAKE/imgs/<img_name>
  outputs/eval/slake_<tag>_preds.jsonl  (baseline / sft_r16 / cpt_sft_r16 / cpt_iu_sft_r16, 有哪个用哪个)
  docs/figures/iu_examples.json (可选): [{"image": path, "gold": str, "pred": str}]
用法: python scripts/make_fig6_examples.py [--qids 1,2,3]
"""
import argparse
import json
import textwrap
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image

REPO = Path(__file__).resolve().parents[1]
RAW, EV, OUT = REPO / "data" / "raw" / "SLAKE", REPO / "outputs" / "eval", REPO / "docs" / "figures"
INK, INK2, GRID = "#0b0b0b", "#52514e", "#e6e5e1"
COL = {"Base": "#2a78d6", "A": "#eb6834", "B1": "#1baf7a", "B2": "#eda100"}
TAGS = [("Base", "baseline"), ("A", "sft_r16"), ("B1", "cpt_sft_r16"), ("B2", "cpt_iu_sft_r16")]
plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 8, "savefig.dpi": 200, "savefig.bbox": "tight",
                     "savefig.facecolor": "white"})


def load_preds(tag):
    p = EV / f"slake_{tag}_preds.jsonl"
    return {json.loads(l)["qid"]: json.loads(l) for l in open(p, encoding="utf-8")} if p.exists() else None


def pick(preds, want):
    """默认挑: 基座错、A 对的题, 每种题型一条, 优先图片不同。"""
    base, a = preds["Base"], preds["A"]
    chosen, used_img = [], set()
    for ct, at in want:
        for q, r in base.items():
            if r["content_type"] == ct and r["answer_type"] == at and r["score"] == 0 and a[q]["score"] == 1 \
                    and META[q]["img_name"] not in used_img and len(r["pred"]) < 40:
                chosen.append(q); used_img.add(META[q]["img_name"]); break
    return chosen


ap = argparse.ArgumentParser()
ap.add_argument("--qids", default="")
args = ap.parse_args()

META = {r["qid"]: r for r in json.load(open(RAW / "test.json", encoding="utf-8")) if r.get("q_lang", "en") == "en"}
preds = {n: load_preds(t) for n, t in TAGS}
preds = {n: p for n, p in preds.items() if p}
qids = [int(x) for x in args.qids.split(",") if x] or pick(preds, [("Abnormality", "OPEN"), ("Position", "OPEN"), ("Organ", "CLOSED")])
iu = json.load(open(OUT / "iu_examples.json", encoding="utf-8")) if (OUT / "iu_examples.json").exists() else []
rows = len(qids) + (1 if iu else 0)

fig = plt.figure(figsize=(8.6, 2.5 * rows + (0.9 if iu else 0)))
gs = fig.add_gridspec(rows, 2, width_ratios=[1, 2.4], height_ratios=[1] * len(qids) + ([1.4] if iu else []), wspace=0.05, hspace=0.25)
for i, q in enumerate(qids):
    m = META[q]
    axi = fig.add_subplot(gs[i, 0]); axt = fig.add_subplot(gs[i, 1]); axt.axis("off")
    axi.imshow(Image.open(RAW / "imgs" / m["img_name"]).convert("RGB")); axi.axis("off")
    axi.set_title(f"{m['modality']} · {m['content_type']} ({m['answer_type'].lower()})", fontsize=8, color=INK2, loc="left")
    y = 0.95
    axt.text(0, y, "Q: " + textwrap.fill(m["question"], 70), va="top", fontsize=8.5, color=INK, weight="bold", transform=axt.transAxes)
    y -= 0.2
    axt.text(0, y, "Gold: " + m["answer"], va="top", fontsize=8.5, color=INK, transform=axt.transAxes)
    y -= 0.18
    for n in preds:
        r = preds[n][q]
        mark = "✓" if r["score"] == 1 else "✗"
        axt.scatter(0.01, y - 0.03, s=30, color=COL[n], transform=axt.transAxes, clip_on=False)
        axt.text(0.05, y, f"{n}: {r['pred']}   {mark}", va="top", fontsize=8.5, color=INK if r["score"] == 1 else INK2,
                 transform=axt.transAxes)
        y -= 0.15
if iu:
    e = iu[0]
    axi = fig.add_subplot(gs[rows - 1, 0]); axt = fig.add_subplot(gs[rows - 1, 1]); axt.axis("off")
    axi.imshow(Image.open(e["image"]).convert("RGB"), cmap="gray"); axi.axis("off")
    axi.set_title("IU X-Ray · report generation after image-text CPT (B2)", fontsize=8, color=INK2, loc="left")
    axt.text(0, 0.88, "Reference report:\n" + textwrap.fill(e["gold"], 78), va="top", fontsize=7.4, color=INK, transform=axt.transAxes)
    axt.text(0, 0.22, "Generated by B2 CPT adapter:\n" + textwrap.fill(e["pred"], 78), va="top", fontsize=7.4, color=INK2, transform=axt.transAxes)
fig.savefig(OUT / "fig6_examples.png")
print("qids:", qids, "->", OUT / "fig6_examples.png")
